<?php

namespace Yoda\EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUpComingEvents($max = null)
    {
        $qb = $this->createQueryBuilder ( 'e' )
            ->addOrderBy ( 'e.time' ,  'ASC' )
            ->andWhere('e.time>:now')
            ->setParameter('now', new \DateTime());

        // if tiver numero max de resultado
        if ($max) {
            $qb->setMaxResults($max);
        }

        // return
        return $qb->getQuery()->execute();
    }

    // ultimos eventos editados
    public function getRecentlyUpdatedEvents()
    {
        return $this->createQueryBuilder('e')
            ->andWhere('e.updatedAt > :since')
            ->setParameter('since', new \DateTime('24 hours ago'))
            ->getQuery()
            ->execute()
            ;
    }
}
